"""baseline: tasks, workflow_definitions, outbox

Revision ID: 63b34ed256fa
Revises:
Create Date: 2026-08-04 14:19:27.701369

The whole schema. Choices worth knowing when reading it:

* ``tasks.id`` / ``outbox.id`` are UUIDs (uuid7, generated app-side and time-ordered, so they
  stay B-tree friendly); ``workflow_definitions.id`` stays a serial because a definition's
  public identity is its ``version``, not a surrogate key.
* ``uq_tasks_title_key`` is named explicitly: duplicate detection matches asyncpg's
  ``UniqueViolationError.constraint_name``, so the name is part of the contract, not incidental.
* Every timestamp is ``timestamptz``; the app stores timezone-aware UTC throughout.
* Both JSON columns are ``JSONB``, not ``JSON`` — they are queried, not just round-tripped.
* The outbox carries two partial indexes rather than one plain one: ``ix_outbox_deliverable``
  covers exactly the relay's poll predicate (pending, not dead-lettered) so undeliverable rows
  cannot accumulate in front of live work, and ``ix_outbox_published_at`` drives the retention
  prune while staying empty for freshly written rows, keeping the request-path insert free of
  index maintenance.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63b34ed256fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_deliverable', 'outbox', ['occurred_at'], unique=False, postgresql_where=sa.text('published_at IS NULL AND dead_lettered_at IS NULL'))
    op.create_index('ix_outbox_published_at', 'outbox', ['published_at'], unique=False, postgresql_where=sa.text('published_at IS NOT NULL'))
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('title_key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_key', name='uq_tasks_title_key')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_version'), 'workflow_definitions', ['version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_definitions_version'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_outbox_published_at', table_name='outbox', postgresql_where=sa.text('published_at IS NOT NULL'))
    op.drop_index('ix_outbox_deliverable', table_name='outbox', postgresql_where=sa.text('published_at IS NULL AND dead_lettered_at IS NULL'))
    op.drop_table('outbox')
    # ### end Alembic commands ###
